// OpenAPI 3.0 spec for the public Katana Pay integration API. Single source of
// truth — served as JSON at /api/openapi and rendered as Swagger UI at /developers.

export const openapiSpec = {
  openapi: "3.0.3",
  info: {
    title: "Katana Pay API",
    version: "1.0.0",
    description: [
      "Server-to-server (S2S) UPI pay-in and payout API for integrating Katana Pay into your platform.",
      "",
      "## Authentication",
      "Each request is authenticated per-merchant with a **Checkout Key + Salt** pair",
      "(issued in the Katana dashboard). You send the public **Key** and a **signature**",
      "(`hash`) of the order fields; the **Salt** stays on your server and is never sent.",
      "",
      "**Signature** — pick the scheme chosen when the Key + Salt was issued:",
      "- `HMAC_SHA256`: `HMAC_SHA256(key + salt, \"txnid|amount|productinfo|email\")` (hex)",
      "- `PAYU_SHA512`: `sha512(\"key|txnid|amount|productinfo|firstname|email|||||||||||salt\")` (hex)",
      "",
      "## Flow",
      "1. `POST /api/v1/katana-pay/order` with the signed order → get QR / deeplinks / `pay_url`.",
      "2. Show the customer the QR or redirect them to `pay_url`.",
      "3. Receive the result via **webhook** (configured in the dashboard) or by polling",
      "   `GET /api/pay-status/{id}` until `terminal: true`.",
      "",
      "## Test mode",
      "Each merchant has a test pair (`mk_test_…`) and a live pair (`mk_live_…`); the Key that signs the order",
      "decides its mode. Test orders pay a sandbox UPI ID and never move real money. For test orders only, the",
      "amount's last two paise digits force outcomes: `.99` → success (~8s), `.11` → expired, `.13` → failed;",
      "anything else stays PENDING. A test order's hosted pay page also has Simulate success / failure buttons.",
      "",
      "## Payouts",
      "Payout requests use the same Key + Salt with a payout-specific signed string (same scheme as above,",
      "different fields, joined with `|`):",
      "- `PAYU_SHA512`: `sha512(\"key|f1|f2|…|salt\")` · `HMAC_SHA256`: `HMAC_SHA256(key + salt, \"f1|f2|…\")`",
      "- register beneficiary: `beneficiary_ref|name|account_number|ifsc|upi_id`",
      "- create payout: `txnid|amount|beneficiary|rail|purpose` (`beneficiary` = the `beneficiary_ref` or `beneficiary_id` you send)",
      "- payout status: `txnid` (or `payout_id`)",
      "A field you leave out is signed as an empty string in its position. `amount` is signed exactly as sent.",
      "",
      "1. Register the beneficiary once. It starts `PENDING`; Katana approves it before it can be paid.",
      "2. `POST /api/v1/payouts/create` — idempotent on `txnid`. **A timeout is not a failure**: retry with the same",
      "   `txnid` or ask `/api/v1/payouts/status`. A new `txnid` is a second payout.",
      "3. Receive the signed `payout.status` callback, or poll status until `terminal: true`. A `SUCCESS` payout can",
      "   still become `REVERSED` if the beneficiary's bank returns it.",
      "A test Key pays out through the payout provider's sandbox only and never moves real money.",
      "",
      "## Going live",
      "A live Key is refused with `403` and `code: LIVE_MODE_NOT_ACTIVATED` until live mode is activated for the",
      "merchant (dashboard: Integration → Activate live mode, approved by Katana).",
    ].join("\n"),
  },
  servers: [{ url: "https://katanapay.co", description: "Production" }],
  tags: [
    { name: "Pay-in", description: "Create and track S2S UPI pay-in orders" },
    { name: "Payout", description: "Register beneficiaries and send payouts (IMPS / NEFT / RTGS / UPI)" },
  ],
  paths: {
    "/api/v1/katana-pay/order": {
      post: {
        tags: ["Pay-in"],
        summary: "Create a pay-in (S2S) order",
        description: "Creates a UPI collect order and returns QR payload, app deeplinks, and a hosted pay URL. Idempotent on `txnid` — re-sending the same `txnid` returns the same order.",
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: { $ref: "#/components/schemas/CreateOrderRequest" },
              examples: {
                qr: {
                  summary: "QR order with customer name + mobile",
                  value: {
                    key: "mk_test_xxx",
                    txnid: "ORDER-1001",
                    amount: "499.00",
                    hash: "<hex signature>",
                    productinfo: "Order 1001",
                    firstname: "Asha Kumar",
                    email: "buyer@example.com",
                    phone: "9999999999",
                    mode: "QR",
                  },
                },
              },
            },
            "application/x-www-form-urlencoded": {
              schema: { $ref: "#/components/schemas/CreateOrderRequest" },
            },
          },
        },
        responses: {
          "201": { description: "Order created", content: { "application/json": { schema: { $ref: "#/components/schemas/CreateOrderResponse" } } } },
          "200": { description: "Existing order returned (same txnid)", content: { "application/json": { schema: { $ref: "#/components/schemas/CreateOrderResponse" } } } },
          "400": { description: "Invalid request / amount", content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } },
          "401": { description: "invalid key or signature mismatch", content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } },
          "403": { description: "Banker is blocked, or a live Key was used before live mode is activated (`code: LIVE_MODE_NOT_ACTIVATED`)", content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } },
        },
      },
    },
    "/api/pay-status/{id}": {
      get: {
        tags: ["Pay-in"],
        summary: "Get order status",
        description: "Public status lookup — the order `id` (UUID) in the URL is the capability. Poll until `terminal` is true.",
        parameters: [
          { name: "id", in: "path", required: true, schema: { type: "string", format: "uuid" }, description: "The `order.id` (UUID) from the create response." },
        ],
        responses: {
          "200": { description: "Order status", content: { "application/json": { schema: { $ref: "#/components/schemas/PayStatus" } } } },
          "404": { description: "Order not found", content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } },
        },
      },
    },
    "/api/v1/payouts/beneficiaries": {
      post: {
        tags: ["Payout"],
        summary: "Register a payout beneficiary",
        description: "Creates the beneficiary `PENDING`; it can be paid once Katana approves it. Re-sending the same `beneficiary_ref` with the same details returns it with its current status (`reused: true`); different details are refused with `409`. Signed string: `beneficiary_ref|name|account_number|ifsc|upi_id`.",
        requestBody: { required: true, content: {
          "application/json": { schema: { $ref: "#/components/schemas/RegisterBeneficiaryRequest" } },
          "application/x-www-form-urlencoded": { schema: { $ref: "#/components/schemas/RegisterBeneficiaryRequest" } },
        } },
        responses: {
          "201": { description: "Registered (PENDING)", content: { "application/json": { schema: { $ref: "#/components/schemas/BeneficiaryResponse" } } } },
          "200": { description: "Already registered with these details", content: { "application/json": { schema: { $ref: "#/components/schemas/BeneficiaryResponse" } } } },
          "400": { description: "Invalid request", content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } },
          "401": { description: "invalid key or signature mismatch", content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } },
          "403": { description: "Live Key before live mode is activated (`code: LIVE_MODE_NOT_ACTIVATED`)", content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } },
          "409": { description: "beneficiary_ref already used with different details", content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } },
        },
      },
    },
    "/api/v1/payouts/create": {
      post: {
        tags: ["Payout"],
        summary: "Create a payout",
        description: "Pays an APPROVED beneficiary. Idempotent on `txnid`: the same `txnid` with the same amount and beneficiary returns the first payout (`200`, `reused: true`); with different values it is refused (`409`). Payouts at or above ₹50,000 wait for approval (`status: ON_HOLD`). Signed string: `txnid|amount|beneficiary|rail|purpose`.",
        requestBody: { required: true, content: {
          "application/json": {
            schema: { $ref: "#/components/schemas/CreatePayoutRequest" },
            examples: { imps: { summary: "IMPS payout to a registered beneficiary", value: {
              key: "mk_test_xxx", txnid: "PO-9001", amount: "1500.00", beneficiary_ref: "vendor-7",
              rail: "IMPS", purpose: "vendor settlement", notify_url: "https://yoursite.com/payout-callback", hash: "<hex signature>",
            } } },
          },
          "application/x-www-form-urlencoded": { schema: { $ref: "#/components/schemas/CreatePayoutRequest" } },
        } },
        responses: {
          "201": { description: "Payout created", content: { "application/json": { schema: { $ref: "#/components/schemas/CreatePayoutResponse" } } } },
          "200": { description: "Existing payout returned (same txnid)", content: { "application/json": { schema: { $ref: "#/components/schemas/CreatePayoutResponse" } } } },
          "400": { description: "Invalid request", content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } },
          "401": { description: "invalid key or signature mismatch", content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } },
          "403": { description: "Live Key before live mode is activated (`code: LIVE_MODE_NOT_ACTIVATED`)", content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } },
          "404": { description: "Beneficiary not found", content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } },
          "409": { description: "Beneficiary not approved, insufficient payout balance, rail not possible for this amount or beneficiary, txnid reused with different values, or test/live mismatch", content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } },
        },
      },
    },
    "/api/v1/payouts/status": {
      post: {
        tags: ["Payout"],
        summary: "Get payout status",
        description: "Look up one payout by your `txnid` or Katana's `payout_id`. A Key only sees payouts of its own mode. Signed string: the `txnid` or `payout_id` you send.",
        requestBody: { required: true, content: {
          "application/json": { schema: { $ref: "#/components/schemas/PayoutStatusRequest" } },
          "application/x-www-form-urlencoded": { schema: { $ref: "#/components/schemas/PayoutStatusRequest" } },
        } },
        responses: {
          "200": { description: "Payout", content: { "application/json": { schema: { type: "object", properties: { payout: { $ref: "#/components/schemas/Payout" } } } } } },
          "401": { description: "invalid key or signature mismatch", content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } },
          "404": { description: "Payout not found", content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } },
        },
      },
    },
  },
  components: {
    schemas: {
      CreateOrderRequest: {
        type: "object",
        required: ["key", "txnid", "amount", "hash"],
        properties: {
          key: { type: "string", description: "Public Checkout Key. `mk_test_…` creates a test order, `mk_live_…` a live one.", example: "mk_test_xxx" },
          txnid: { type: "string", maxLength: 60, description: "Your unique order id (idempotency key).", example: "ORDER-1001" },
          amount: { type: "string", description: "Major-unit amount as a string.", example: "499.00" },
          hash: { type: "string", description: "Signature over the order (see Authentication)." },
          productinfo: { type: "string", description: "Order description (must match what you signed).", example: "Order 1001" },
          firstname: { type: "string", description: "Customer name (also part of the PAYU signature).", example: "Asha Kumar" },
          email: { type: "string", description: "Customer email (must match what you signed).", example: "buyer@example.com" },
          phone: { type: "string", description: "Customer mobile number.", example: "9999999999" },
          customer_vpa: { type: "string", description: "Payer (sender) UPI VPA.", example: "buyer@upi" },
          receiver_vpa: { type: "string", description: "Single receiver VPA (overrides banker default)." },
          receiver_vpas: { type: "array", items: { type: "string" }, maxItems: 30, description: "Receiver VPA pool with backup failover. Defaults to the banker's settlement VPA." },
          mode: { type: "string", enum: ["QR", "INTENT"], default: "QR", description: "QR shows a scannable code; INTENT returns app deeplinks." },
          currency: { type: "string", default: "INR", example: "INR" },
        },
      },
      CreateOrderResponse: {
        type: "object",
        properties: {
          verified: { type: "boolean", example: true },
          merchant: { type: "string", example: "K-001" },
          reused: { type: "boolean", description: "true when an existing order matched the txnid." },
          livemode: { type: "boolean", description: "false when the order was created with a test Key.", example: true },
          order: { $ref: "#/components/schemas/Order" },
          deeplinks: {
            type: "object",
            properties: {
              upi: { type: "string", example: "upi://pay?pa=...&am=499.00..." },
              paytm: { type: "string", example: "paytmmp://pay?..." },
              phonepe: { type: "string", example: "phonepe://pay?..." },
            },
          },
          upi_intent: { type: "string", example: "upi://pay?pa=...&am=499.00..." },
          qr_payload: { type: "string", description: "Render this string as a QR code.", example: "upi://pay?pa=...&am=499.00..." },
          pay_url: { type: "string", description: "Hosted pay page — redirect the customer here.", example: "https://katanapay.co/pay/<uuid>" },
        },
      },
      Order: {
        type: "object",
        properties: {
          id: { type: "string", format: "uuid", description: "Internal order id — use for /api/pay-status/{id}." },
          order_id: { type: "string", example: "ORDER-1001" },
          amount: { type: "number", example: 499 },
          currency_code: { type: "string", example: "INR" },
          status: { type: "string", enum: ["PENDING", "SUCCESS", "FAILED", "EXPIRED"], example: "PENDING" },
        },
      },
      PayStatus: {
        type: "object",
        properties: {
          order_id: { type: "string", example: "ORDER-1001" },
          amount: { type: "number", example: 499 },
          status: { type: "string", enum: ["PENDING", "SUCCESS", "FAILED", "EXPIRED"], example: "SUCCESS" },
          terminal: { type: "boolean", description: "true once the status is final.", example: true },
          rrn: { type: "string", description: "Bank UTR / RRN once paid.", example: "455537238396" },
          livemode: { type: "boolean", description: "false for a test order.", example: true },
        },
      },
      RegisterBeneficiaryRequest: {
        type: "object",
        required: ["key", "hash", "beneficiary_ref", "name"],
        description: "Send `account_number` + `ifsc`, or `upi_id` (or both).",
        properties: {
          key: { type: "string", example: "mk_test_xxx" },
          hash: { type: "string", description: "Signature over `beneficiary_ref|name|account_number|ifsc|upi_id`." },
          beneficiary_ref: { type: "string", pattern: "^[A-Za-z0-9_-]{1,40}$", description: "Your id for this beneficiary.", example: "vendor-7" },
          name: { type: "string", maxLength: 100, example: "Asha Traders" },
          account_number: { type: "string", pattern: "^[A-Za-z0-9]{6,20}$", example: "001122334455" },
          ifsc: { type: "string", pattern: "^[A-Z]{4}0[A-Z0-9]{6}$", example: "HDFC0001234" },
          upi_id: { type: "string", example: "asha@okhdfc" },
          bank_name: { type: "string", description: "Display only; not signed." },
        },
      },
      BeneficiaryResponse: {
        type: "object",
        properties: {
          reused: { type: "boolean" },
          beneficiary: { type: "object", properties: {
            beneficiary_id: { type: "string", format: "uuid" },
            beneficiary_ref: { type: "string", example: "vendor-7" },
            status: { type: "string", enum: ["PENDING", "APPROVED", "REJECTED", "DISABLED"], example: "PENDING" },
            name: { type: "string" },
            account_last4: { type: "string", nullable: true, example: "4455" },
            ifsc: { type: "string", nullable: true },
            upi_id: { type: "string", nullable: true },
          } },
        },
      },
      CreatePayoutRequest: {
        type: "object",
        required: ["key", "hash", "txnid", "amount"],
        description: "Send exactly one of `beneficiary_ref` or `beneficiary_id`.",
        properties: {
          key: { type: "string", description: "`mk_test_…` pays out in the provider's sandbox; `mk_live_…` moves real money.", example: "mk_test_xxx" },
          hash: { type: "string", description: "Signature over `txnid|amount|beneficiary|rail|purpose`." },
          txnid: { type: "string", pattern: "^[A-Za-z0-9_-]{1,40}$", description: "Your unique payout id (idempotency key).", example: "PO-9001" },
          amount: { type: "string", pattern: "^\\d+(\\.\\d{1,2})?$", description: "Rupees as a string, at most 2 decimals. Signed exactly as sent.", example: "1500.00" },
          beneficiary_ref: { type: "string", example: "vendor-7" },
          beneficiary_id: { type: "string", format: "uuid" },
          rail: { type: "string", enum: ["IMPS", "NEFT", "RTGS", "UPI"], description: "Default: IMPS for a bank beneficiary, UPI for a UPI-only one. IMPS ≤ ₹5,00,000; RTGS ≥ ₹2,00,000." },
          purpose: { type: "string", maxLength: 50, example: "vendor settlement" },
          currency: { type: "string", enum: ["INR"], default: "INR" },
          notify_url: { type: "string", description: "Where the signed payout.status callback goes (http/https). Default: your webhook URL." },
        },
      },
      CreatePayoutResponse: {
        type: "object",
        properties: {
          payout: { $ref: "#/components/schemas/Payout" },
          reused: { type: "boolean", description: "true when an existing payout matched the txnid." },
          approval_required: { type: "boolean", description: "true when the payout waits for approval (≥ ₹50,000)." },
        },
      },
      PayoutStatusRequest: {
        type: "object",
        required: ["key", "hash"],
        description: "Send exactly one of `txnid` or `payout_id`.",
        properties: {
          key: { type: "string" },
          hash: { type: "string", description: "Signature over the `txnid` or `payout_id` you send." },
          txnid: { type: "string" },
          payout_id: { type: "string" },
        },
      },
      Payout: {
        type: "object",
        properties: {
          payout_id: { type: "string", example: "PO-3FA2C19B7D10" },
          txnid: { type: "string", example: "PO-9001" },
          status: { type: "string", enum: ["PROCESSING", "ON_HOLD", "SUCCESS", "FAILED", "REJECTED", "REVERSED"], example: "PROCESSING" },
          terminal: { type: "boolean", description: "true for SUCCESS, FAILED, REJECTED and REVERSED. SUCCESS can still become REVERSED." },
          amount: { type: "string", example: "1500.00" },
          currency: { type: "string", example: "INR" },
          rail: { type: "string", nullable: true, example: "IMPS" },
          beneficiary_id: { type: "string", format: "uuid" },
          utr: { type: "string", nullable: true, description: "Bank reference once paid.", example: "327012345470" },
          failure_reason: { type: "string", nullable: true },
          livemode: { type: "boolean" },
          created_at: { type: "string", format: "date-time" },
          completed_at: { type: "string", format: "date-time", nullable: true },
        },
      },
      Error: {
        type: "object",
        properties: { error: { type: "string", example: "signature mismatch" } },
      },
    },
  },
  "x-webhooks": {
    "payment.status": {
      post: {
        summary: "Payment status webhook (Katana → your server)",
        description: [
          "When you set a Webhook URL in the dashboard, Katana POSTs a signed JSON event on each status change.",
          "Headers: `X-Event-Type`, `X-Timestamp`, `X-Payload-Hash` (sha256 of body), `X-Signature` = `HMAC_SHA256(webhook_secret, payloadHash + \".\" + timestamp)`, `X-Attempt`.",
          "Verify: reject if `X-Timestamp` skew > ±5 min; recompute and compare the signature (timing-safe); return 2xx.",
          "Retries: 1m → 5m → 15m → 1h → 6h → 24h then dead-letter. Make your handler idempotent.",
        ].join(" "),
      },
    },
    "payout.status": {
      post: {
        summary: "Payout status callback (Katana → your server)",
        description: [
          "Sent when a payout reaches SUCCESS, FAILED, REJECTED or REVERSED — once per status — to the payout's `notify_url`, else your webhook URL.",
          "JSON body: `EVENT` (`payout.status`), `PAYOUT_ID`, `ORDER_ID` (your txnid), `AMOUNT`, `CURRENCY_CODE` (`356`), `STATUS`, `RAIL`, `UTR`,",
          "`FAILURE_REASON`, `RESPONSE_DATE_TIME`, `LIVEMODE` (`false`, test payouts only) and `HASH`.",
          "Verify `HASH` exactly like the pay-in callback: every field except HASH, sorted by name (byte order), joined as `NAME=value` with `~`,",
          "your Salt (of the payout's mode) appended, SHA-256, uppercase hex. Empty values stay in (`UTR=`). Return 2xx; retries follow the schedule above.",
        ].join(" "),
      },
    },
  },
} as const;
